### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by dodyrr** [timctho/convolutional-pose-machines-tensorflow#21]
i found this error how to fix this?
Traceback (most recent call last):
  File "C:/Users/dody/Desktop/convolutional-pose-machines-tensorflow-master/demo_cpm_hand.py", line 430, in <module>
    tf.app.run()
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "C:/Users/dody/Desktop/convolutional-pose-machines-tensorflow-master/demo_cpm_hand.py", line 106, in main
    model = cpm_hand.CPM_Model(FLAGS.stages, FLAGS.joints + 1)
TypeError: __init__() missing 2 required positional arguments: 'stages' and 'joints'

**Comment by timctho** [comment]
Please try new scripts starting with 'run'.
