### ISSUE TITLE
Error running demo_cpm_hand.py

### ISSUE THREAD

**Issue by LalitPradhan** [timctho/convolutional-pose-machines-tensorflow#25]
I get the following error:

ValueError: Dimension 3 in both shapes must be equal, but are 23 and 22. Shapes are [1,1,512,23] and [1,1,512,22]. for 'Assign_32' (op: 'Assign') with input shapes: [1,1,512,23], [1,1,512,22].

This is when i pass finetune = False in load weights.

**Comment by LalitPradhan** [comment]
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2018-03-31 16:21:07.701128: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "demo_cpm_hand.py", line 431, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "demo_cpm_hand.py", line 118, in main
    model.load_weights_from_file(FLAGS.model_path, sess, False)
  File "/home/lalit/Desktop/Lalit/Office/Video_Tracking/convolutional-pose-machines-tensorflow/models/nets/cpm_hand.py", line 395, in load_weights_from_file
    sess.run(tf.assign(conv_kernel, loaded_kernel))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 281, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3292, in create_op
    compute_device=compute_device)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3332, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2496, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2469, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2399, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 3 in both shapes must be equal, but are 23 and 22. Shapes are [1,1,512,23] and [1,1,512,22]. for 'Assign_32' (op: 'Assign') with input shapes: [1,1,512,23], [1,1,512,22].

**Comment by Metal-joker** [comment]
Did you train your own model?

**Comment by LalitPradhan** [comment]
No. I tried to use the pretrained weights given in hand_cpm pickle file.

**Comment by xiezhongzhao** [comment]
model.build_model(input_data, center_map, 1)

I get the following error:
AttributeError: "CPM_Model" object has no attribute 'build_model'

**Comment by xiezhongzhao** [comment]
running demo_cpm_hand.py error: 
Traceback (most recent call last):
  File "/home/xc/xzz/hand/demo_cpm_hand.py", line 437, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/xc/xzz/hand/demo_cpm_hand.py", line 121, in main
    model.load_weights_from_file(FLAGS.model_path, sess, False)
  File "/home/xc/xzz/hand/cpm_hand_slim.py", line 128, in load_weights_from_file
    conv_kernel = tf.get_variable('sub_stages/sub_conv' + str(layer) + '/kernel')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 760, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable sub_stages/sub_conv1/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

I run demo_cpm_hand.py, it worked, the structure is very similar between demo_cpm_hand and demo_cpm_body,but the errors above happened when I run demo_hand.py.

**Comment by SubhiH** [comment]
I was able to run the demo **run_demo_hand_with_tracker.py**  after some modifications.

1. Make sure that the model is in the path _models/weights/cpm_hand.pkl_ .
2. Put this in line 59

`model.load_weights_from_file("models/weights/cpm_hand.pkl",sess,False);`
3. Comment If else
`# if FLAGS.model_path.endswith('pkl'):
        #     model.load_weights_from_file(FLAGS.model_path, sess, False)
        # else:
        #     saver.restore(sess, 'models/weights/cpm_hand.pkl')`

**Comment by moon05** [comment]
@xiezhongzhao Were you able to solve this? I am also facing the same issue!

**Comment by ArgentumWalker** [comment]
@moon05 Hi! I've just solved it in pull request #34. Also note that there is no default testing image for this demo in test_imgs/ folder, it may cause error if you don't use `DEMO_TYPE` flag when running the demo.
