### ISSUE TITLE
convolutional-pose-machines-tensorflow

### ISSUE THREAD

**Issue by JasOlean** [timctho/convolutional-pose-machines-tensorflow#30]
How can I fix this error?

Traceback (most recent call last):
  File "D:/convolutional-pose-machines-tensorflow-master/convolutional-pose-machines-tensorflow-master/demo_cpm_hand.py", line 431, in <module>
    tf.app.run()
  File "C:\Users\Khin Sabai\PycharmProjects\PythonRun\venv\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "D:/convolutional-pose-machines-tensorflow-master/convolutional-pose-machines-tensorflow-master/demo_cpm_hand.py", line 106, in main
    model = cpm_hand.CPM_Model(FLAGS.stages, FLAGS.joints + 1)
TypeError: __init__() missing 2 required positional arguments: 'stages' and 'joints'

**Comment by woxinguo** [comment]
have same error,you can looked at the source  of 'CPM_Model',and give this function two another parameters

**Comment by woxinguo** [comment]
class CPM_Model(CPM):
    def __init__(self, input_size, heatmap_size, stages, joints, img_type='RGB', is_training=True):
